name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Insall NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check node version
        run: node -v
      - name: Build project
        run: echo "building project..."
