name: Matrix Demo
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          # If you just need node 18 on ubuntu-latest instead of both windows-latest and ubuntu-latest
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Insall NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check node version
        run: node -v
      - name: Build project
        run: echo "building project..."
